# Generated by Django 5.0.7 on 2024-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='currency_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
