# Generated by Django 5.0.7 on 2024-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_userpreferences_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='rows_per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
