# Generated by Django 5.0.7 on 2024-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_userpreferences_rows_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='rows_per_page',
            field=models.IntegerField(default=25),
        ),
    ]
