# Generated by Django 5.0.7 on 2024-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0005_alter_userpreferences_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='accounts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='categories_expenses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='categories_incomes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(default='EUR - Euro', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
