# Generated by Django 5.0.7 on 2024-08-18 18:18

import userpreferences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0007_alter_userpreferences_categories_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='categories_expenses',
            field=models.JSONField(default=userpreferences.models.get_default_categories_expenses),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='categories_incomes',
            field=models.JSONField(default=userpreferences.models.get_default_categories_incomes),
        ),
    ]
