# Generated by Django 5.0.7 on 2024-08-20 16:06

import userpreferences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0008_alter_userpreferences_categories_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='accounts',
            field=models.JSONField(default=userpreferences.models.get_default_accounts),
        ),
    ]
